apiVersion: v1
kind: ConfigMap
metadata:
  name: nexusflow-config
  namespace: nexusflow
data:
  SPRING_PROFILES_ACTIVE: "prod"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
  REDIS_HOST: "redis-master.redis.svc.cluster.local"
  REDIS_PORT: "6379"
  MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED: "true"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "0.5"
