apiVersion: v1
kind: Secret
metadata:
  name: nexusflow-secrets
  namespace: nexusflow
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-cluster.postgres.svc.cluster.local:5432/${DB_NAME}"
  SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
  SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
  JWT_SECRET: "${JWT_SECRET}"
