apiVersion: v1
kind: Secret
metadata:
  name: nexusflow-secrets
  namespace: nexusflow
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-cluster.postgres.svc.cluster.local:5432/nexusflow_prod_db"
  SPRING_DATASOURCE_USERNAME: "nexusflow_prod_user"
  SPRING_DATASOURCE_PASSWORD: "SuperSecureProductionPassword123!"
  JWT_SECRET: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
