apiVersion: v1
kind: Service
metadata:
  name: nexusflow-service
  namespace: nexusflow
  labels:
    app: nexusflow-api
spec:
  type: ClusterIP
  selector:
    app: nexusflow-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
